[tool.black]
line-length = 88
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | typings
)/
'''

[tool.isort]
profile = "black"

[tool.flake8]
per-file-ignores = [
    '__init__.py:F401',
]
max-line-length = 88
count = true

[tool.pyright]
pythonVersion = "3.10"
exclude = [
    "**/__pycache__",
    "typings",
]
stubPath = [
    "typings",
]
