"""
This type stub file was generated by pyright.
"""

from logging import Logger

"""Custom logging for notion-sdk-py."""
def make_console_logger() -> Logger:
    """Return a custom logger."""
    ...

