"""
This type stub file was generated by pyright.
"""

from typing import Awaitable, TypeVar, Union

"""Custom type definitions for notion-sdk-py."""
T = TypeVar("T")
SyncAsync = Union[T, Awaitable[T]]
