"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function

from fire.core import Fire

"""
This type stub file was generated by pyright.
"""
__all__ = ['Fire']
__version__ = ...
