"""
This type stub file was generated by pyright.
"""

from fire import testutils
from hypothesis import example, given, settings, strategies as st

"""
This type stub file was generated by pyright.
"""
class DocstringsFuzzTest(testutils.BaseTestCase):
  @settings(max_examples=1000, deadline=1000)
  @given(st.text(min_size=1))
  @example('This is a one-line docstring.')
  def test_fuzz_parse(self, value):
    ...
  


if __name__ == '__main__':
  ...
