"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""
This type stub file was generated by pyright.
"""
LINE_LENGTH = ...
class FormattingTest(testutils.BaseTestCase):
  def test_bold(self):
    ...
  
  def test_underline(self):
    ...
  
  def test_indent(self):
    ...
  
  def test_indent_multiple_lines(self):
    ...
  
  def test_wrap_one_item(self):
    ...
  
  def test_wrap_multiple_items(self):
    ...
  
  def test_ellipsis_truncate(self):
    ...
  
  def test_ellipsis_truncate_not_enough_space(self):
    ...
  
  def test_ellipsis_middle_truncate(self):
    ...
  
  def test_ellipsis_middle_truncate_not_enough_space(self):
    ...
  


if __name__ == '__main__':
  ...
