"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
LINE_LENGTH = ...
SECTION_INDENTATION = ...
SUBSECTION_INDENTATION = ...
def HelpText(component, trace=..., verbose=...):
  """Gets the help string for the current component, suitable for a help screen.

  Args:
    component: The component to construct the help string for.
    trace: The Fire trace of the command so far. The command executed so far
      can be extracted from this trace.
    verbose: Whether to include private members in the help screen.

  Returns:
    The full help screen as a string.
  """
  ...

def UsageText(component, trace=..., verbose=...):
  """Returns usage text for the given component.

  Args:
    component: The component to determine the usage text for.
    trace: The Fire trace object containing all metadata of current execution.
    verbose: Whether to display the usage text in verbose mode.

  Returns:
    String suitable for display in an error screen.
  """
  ...

class ActionGroup:
  """A group of actions of the same kind."""
  def __init__(self, name, plural) -> None:
    ...
  
  def Add(self, name, member=...):
    ...
  
  def GetItems(self):
    ...
  


