"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def Embed(variables, verbose=...):
  """Drops into a Python REPL with variables available as local variables.

  Args:
    variables: A dict of variables to make available. Keys are variable names.
        Values are variable values.
    verbose: Whether to include 'hidden' members, those keys starting with _.
  """
  ...

