"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""
This type stub file was generated by pyright.
"""
class MainModuleTest(testutils.BaseTestCase):
  """Tests to verify the behavior of __main__ (python -m fire)."""
  def testNameSetting(self):
    ...
  
  def testArgPassing(self):
    ...
  


class MainModuleFileTest(testutils.BaseTestCase):
  """Tests to verify correct import behavior for file executables."""
  def setUp(self):
    ...
  
  def testFileNameFire(self):
    ...
  
  def testFileNameFailure(self):
    ...
  
  def testFileNameModuleDuplication(self):
    ...
  
  def testFileNameModuleFileFailure(self):
    ...
  


if __name__ == '__main__':
  ...
