"""
This type stub file was generated by pyright.
"""

from mal.anime import Anime, AnimeCharacterResult, AnimeStaffResult
from mal.anime_search import AnimeSearch, AnimeSearchResult
from mal._manga import Manga, MangaCharacterResult
from mal._manga_search import MangaSearch, MangaSearchResult

