"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Tuple

from mal import _base
from mal._base import _Base

class _MAL(_Base):
    def __init__(self, mal_id, mal_type, timeout) -> None:
        ...
    
    @property
    @_base.property
    def mal_id(self) -> int:
        ...
    
    @property
    @_base.property
    def title(self) -> str:
        ...
    
    @property
    @_base.property
    def title_english(self) -> str:
        ...
    
    @property
    @_base.property
    def title_japanese(self) -> str:
        ...
    
    @property
    @_base.property_list
    def title_synonyms(self) -> List[str]:
        ...
    
    @property
    @_base.property
    def url(self) -> str:
        ...
    
    @property
    @_base.property
    def image_url(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def type(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def status(self) -> Optional[str]:
        ...
    
    @property
    @_base.property_list
    def genres(self) -> List[str]:
        ...
    
    @property
    @_base.property_list
    def themes(self) -> List[str]:
        ...
    
    @property
    @_base.property_list
    def external_links(self) -> List[Tuple[str, str]]:
        ...
    
    @property
    @_base.property
    def score(self) -> Optional[float]:
        ...
    
    @property
    @_base.property
    def scored_by(self) -> Optional[int]:
        ...
    
    @property
    @_base.property
    def rank(self) -> Optional[int]:
        ...
    
    @property
    @_base.property
    def popularity(self) -> Optional[int]:
        ...
    
    @property
    @_base.property
    def members(self) -> Optional[int]:
        ...
    
    @property
    @_base.property
    def favorites(self) -> Optional[int]:
        ...
    


