"""
This type stub file was generated by pyright.
"""

from typing import List, Optional

from mal import _base
from mal._search import _Search, _SearchResult

class MangaSearchResult(_SearchResult):
    def __init__(self, tds) -> None:
        """
        Manga search result
        """
        ...
    
    @property
    def mal_id(self) -> int:
        ...
    
    @property
    def title(self) -> str:
        ...
    
    @property
    def url(self) -> str:
        ...
    
    @property
    def image_url(self) -> str:
        ...
    
    @property
    def type(self) -> Optional[str]:
        ...
    
    @property
    def score(self) -> Optional[float]:
        ...
    
    @property
    def synopsis(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def volumes(self) -> Optional[int]:
        ...
    


class MangaSearch(_Search):
    def __init__(self, query: str, timeout: int = ...) -> None:
        """
        Manga search by query
        """
        ...
    
    def reload(self) -> None:
        """
        Reload manga search
        """
        ...
    
    @property
    @_base.property_list
    def results(self) -> List[MangaSearchResult]:
        ...
    


