"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional, Tuple

from mal import _base
from mal._mal import _MAL

class AnimeCharacterResult:
    def __init__(self, name, role, voice_actor) -> None:
        """
        Anime character result
        """
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @property
    def role(self) -> str:
        ...
    
    @property
    def voice_actor(self) -> str:
        ...
    


class AnimeStaffResult:
    def __init__(self, name, role) -> None:
        """
        Anime staff result
        """
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @property
    def role(self) -> str:
        ...
    


class Anime(_MAL):
    def __init__(self, mal_id: int, timeout: int = ...) -> None:
        """
        Anime query by ID
        """
        ...
    
    def reload(self) -> None:
        """
        Reload anime query
        """
        ...
    
    @property
    def mal_id(self) -> int:
        ...
    
    @property
    def title(self) -> str:
        ...
    
    @property
    def title_english(self) -> str:
        ...
    
    @property
    def title_japanese(self) -> str:
        ...
    
    @property
    def title_synonyms(self) -> List[str]:
        ...
    
    @property
    def url(self) -> str:
        ...
    
    @property
    def image_url(self) -> str:
        ...
    
    @property
    def type(self) -> Optional[str]:
        ...
    
    @property
    def status(self) -> Optional[str]:
        ...
    
    @property
    def genres(self) -> List[str]:
        ...
    
    @property
    def themes(self) -> List[str]:
        ...
    
    @property
    def external_links(self) -> List[Tuple[str, str]]:
        """Return List of Tuples containing name and url"""
        ...
    
    @property
    def score(self) -> Optional[float]:
        ...
    
    @property
    def scored_by(self) -> Optional[int]:
        ...
    
    @property
    def rank(self) -> Optional[int]:
        ...
    
    @property
    def popularity(self) -> Optional[int]:
        ...
    
    @property
    def members(self) -> Optional[int]:
        ...
    
    @property
    def favorites(self) -> Optional[int]:
        ...
    
    @property
    @_base.property
    def episodes(self) -> Optional[int]:
        ...
    
    @property
    @_base.property
    def aired(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def premiered(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def broadcast(self) -> Optional[str]:
        ...
    
    @property
    @_base.property_list
    def producers(self) -> List[str]:
        ...
    
    @property
    @_base.property_list
    def licensors(self) -> List[str]:
        ...
    
    @property
    @_base.property_list
    def studios(self) -> List[str]:
        ...
    
    @property
    @_base.property
    def source(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def duration(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def rating(self) -> Optional[str]:
        ...
    
    @property
    @_base.property_dict
    def related_anime(self) -> Dict[str, List[str]]:
        ...
    
    @property
    @_base.property_list
    def opening_themes(self) -> List[str]:
        ...
    
    @property
    @_base.property_list
    def ending_themes(self) -> List[str]:
        ...
    
    @property
    @_base.property_list
    def characters(self) -> List[AnimeCharacterResult]:
        ...
    
    @property
    @_base.property_list
    def staff(self) -> List[AnimeStaffResult]:
        ...
    
    @property
    @_base.property
    def synopsis(self) -> Optional[str]:
        ...
    
    @property
    @_base.property
    def background(self) -> Optional[str]:
        ...
    


