"""
This type stub file was generated by pyright.
"""

from typing import Callable

def property(func: Callable) -> Callable:
    ...

def property_list(func: Callable) -> Callable:
    ...

def property_dict(func: Callable) -> Callable:
    ...

class _Base:
    def __init__(self, timeout) -> None:
        ...
    


