"""
This type stub file was generated by pyright.
"""

from typing import Optional

from mal import _base
from mal._base import _Base

class _SearchResult:
    _image_url_path_regex = ...
    _mal_id_regex = ...
    def __init__(self, tds) -> None:
        ...
    
    @property
    @_base.property
    def url(self) -> str:
        ...
    
    @property
    @_base.property
    def mal_id(self) -> int:
        ...
    
    @property
    @_base.property
    def image_url(self) -> str:
        ...
    
    @property
    @_base.property
    def title(self) -> str:
        ...
    
    @property
    @_base.property
    def synopsis(self) -> str:
        ...
    
    @property
    @_base.property
    def type(self) -> str:
        ...
    
    @property
    @_base.property
    def score(self) -> Optional[float]:
        ...
    


class _Search(_Base):
    def __init__(self, query, mal_type, timeout) -> None:
        ...
    


