name: Python Lint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  codecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: false
          virtualenvs-in-project: false
      - name: Install dependencies using Poetry
        run: poetry install --no-interaction

      - name: Check linter with ruff and pyright
        run: poetry run poe lint